---
language: python
python: "2.7"
sudo: required
dist: trusty

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

script:
  # We'll add some commands to test the role here.
  - "ansible-playbook -i tests/testinventory tests/test.yml -vv --syntax-check"

  - "ansible-playbook -i tests/testinventory tests/test.yml -vv --connection=local --sudo"

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/testinventory tests/test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)


  # Make sure Pet Clinic is running.
  - >
    curl --insecure -s -o /dev/null -w "%{http_code}" http://localhost:80
    | grep -q '200'
    && (echo 'Status code 200 test: pass' && exit 0)
    || (echo 'Status code 200 test: fail' && exit 1)
