---
language: python
python: "2.7"
sudo: required
dist: trusty

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

script:
  # Check playbook syntac
  - "ansible-playbook -i tests/testinventory tests/test.yml -vv --syntax-check"

 # Check playbook runs successfully
  - "ansible-playbook -i tests/testinventory tests/test.yml -vv --connection=local --sudo"

  # Make sure Pet Clinic is running.
  - >
    curl --insecure -s -o /dev/null -w "%{http_code}" http://localhost:80
    | grep -q '200'
    && (echo 'Status code 200 test: pass' && exit 0)
    || (echo 'Status code 200 test: fail' && exit 1)
