## Customize deployment commands
deployment:
  staging:
    branch: master
    heroku:
      appname: foo-bar-123

version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout:
          post:
            - git clone https://github.com/secretescapes/grails-petclinic
      - run: echo "BUILD START..."
      - run: ls
      - run: ./grailsw war

  test:
    docker:
      - image: circleci/python:2.7
    steps:
#      - checkout:
#          post:
#              - git clone ...

      - run: pip install ansible

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build