## Customize deployment commands
deployment:
  staging:
    branch: master
    heroku:
      appname: foo-bar-123

version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
        command: echo "BUILD START..."
        command: ./grailsw war target/petclinic.war

  test:
    docker:
      - image: circleci/python:2.7
    steps:
#      - checkout
#          post:
#              - git clone ...

      - run:
        docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build