version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: echo "BUILD START..."
      - run: git clone --branch 3.0 https://github.com/secretescapes/grails-petclinic
      - run: cd grails-petclinic && ./grailsw war
      - store_artifacts:
          path: grails-petclinic/target/petclinic-3.0.war

  test:
    docker:
      - image: circleci/python:2.7
    steps:
#      - checkout:
#          post:
#              - git clone ...

      - run: sudo pip install ansible
      - run: cp $CIRCLE_ARTIFACTS/petclinic-3.0.war target/petclinic-3.0.war
      - run: ansible-playbook -i tests/testinventory tests/test.yml -vv --syntax-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build